version: '3'
volumes:
  mongodata:
    external: true
services:
  mongo:
    container_name: lab-mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    command: ["redis-server"]
    hostname: redis
  labs:
    container_name: labs
    links:
      - mongo
      - redis
    build: .
    volumes:
      - ./:/app
      - /app/node_modules/
    working_dir: /app
    environment:
      WORKING_ENV: "dev"
      MONGO_URI: "mongodb://mongo:27017/lab-mongo"
      LOGGER_KEY: "123456"
      REDIS_URL: "redis://cache"
      habijabi: "asdhasghkdasgdgas"
      PORT: 8080
    ports:
      - "8080:8080"